// data.js dados de exemplo que servem como banco de dados para alguns testes
export let users = [
    {
      id: 1,
      nome: "Lucas Araujo",
      dataNascimento: "1995-05-10",
      telefone: "(92) 99999-8888",
      email: "lucas@email.com",
      estadoCivil: "solteiro",
      sexo: "masculino",
      cep: "69000-000",
      endereco: "Rua Exemplo, 123",
      bairro: "Centro",
      cidade: "Manaus",
      estado: "AM",
      pais: "Brasil",
      usuario: "lucasaraujo",
      departamento: "TI",
      emailCorp: "lucas.araujo@empresa.com",
      ativo: "sim",
      dataAdmissao: "2023-01-15",
      numeroIdentidade: "12345678",
      numeroCpf: "11122233344"
    },
    {
      id: 2,
      nome: "Maria Silva",
      dataNascimento: "1988-03-22",
      telefone: "(11) 98765-4321",
      email: "maria.silva@email.com",
      estadoCivil: "casada",
      sexo: "feminino",
      cep: "01000-000",
      endereco: "Av. Paulista, 456",
      bairro: "Bela Vista",
      cidade: "São Paulo",
      estado: "SP",
      pais: "Brasil",
      usuario: "mariasilva",
      departamento: "Recursos Humanos",
      emailCorp: "maria.silva@empresa.com",
      ativo: "sim",
      dataAdmissao: "2022-08-10",
      numeroIdentidade: "87654321",
      numeroCpf: "22233344455"
    },
    {
      id: 3,
      nome: "João Santos",
      dataNascimento: "1990-12-03",
      telefone: "(21) 97777-5555",
      email: "joao.santos@email.com",
      estadoCivil: "solteiro",
      sexo: "masculino",
      cep: "20000-000",
      endereco: "Rua Copacabana, 789",
      bairro: "Copacabana",
      cidade: "Rio de Janeiro",
      estado: "RJ",
      pais: "Brasil",
      usuario: "joaosantos",
      departamento: "Vendas",
      emailCorp: "joao.santos@empresa.com",
      ativo: "sim",
      dataAdmissao: "2021-03-20",
      numeroIdentidade: "45612378",
      numeroCpf: "33344455566"
    },
    {
      id: 4,
      nome: "Ana Costa",
      dataNascimento: "1985-07-18",
      telefone: "(85) 96666-3333",
      email: "ana.costa@email.com",
      estadoCivil: "casada",
      sexo: "feminino",
      cep: "60000-000",
      endereco: "Rua Dragão do Mar, 321",
      bairro: "Praia de Iracema",
      cidade: "Fortaleza",
      estado: "CE",
      pais: "Brasil",
      usuario: "anacosta",
      departamento: "Financeiro",
      emailCorp: "ana.costa@empresa.com",
      ativo: "sim",
      dataAdmissao: "2020-11-05",
      numeroIdentidade: "78945612",
      numeroCpf: "44455566677"
    },
    {
      id: 5,
      nome: "Pedro Oliveira",
      dataNascimento: "1992-09-14",
      telefone: "(31) 95555-2222",
      email: "pedro.oliveira@email.com",
      estadoCivil: "solteiro",
      sexo: "masculino",
      cep: "30000-000",
      endereco: "Av. Afonso Pena, 654",
      bairro: "Centro",
      cidade: "Belo Horizonte",
      estado: "MG",
      pais: "Brasil",
      usuario: "pedrooliveira",
      departamento: "Marketing",
      emailCorp: "pedro.oliveira@empresa.com",
      ativo: "não",
      dataAdmissao: "2019-06-12",
      numeroIdentidade: "15975346",
      numeroCpf: "55566677788"
    }
  ];